version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    command: server
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DISPLAY=${DISPLAY}
    command: client
    depends_on:
      - server
